### ISSUE TITLE
怎么运行不了？

### ISSUE THREAD

**Issue by johnson-xu01** [conancome/A-Simple-Chatbot#2]
![image](https://cloud.githubusercontent.com/assets/18277731/23066384/46951536-f555-11e6-8e08-e1188880ef54.png)

**Comment by Jorbe-Jiang** [comment]
你把main.py文件里的最后build_hash_table()函数注释掉，因为这个函数只在第一次训练的适合需要用到，当你运行一次main.py后就不再需要build_bash_table()了。。
